apiVersion: apps/v1
kind: Deployment
metadata:
  name: graduateapp
  namespace: graduateapp
  labels:
    app: graduateapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: graduateapp
  template:
    metadata:
      labels:
        app: graduateapp
    spec:
      containers:
      - name: graduateapp
        image: plonqnet/graduateapp
        resources:
          requests:
            cpu: "1"
            memory: "200Mi"
          limits:
            cpu: "2"
            memory: "400Mi"
        ports:
        - containerPort: 80


apiVersion: v1
kind: Service
metadata:
  name: graduateapp
  namespace: graduateapp
spec:
  type: NodePort
  selector:
    app: graduateapp
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30429